name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.41.3
    with:
      image: ghcr.io/radiorabe/mediamtx
      name: mediamtx
      display-name: RaBe MediaMTX
      tags: rhel9 mediamtx rabe
      cosign-verify: false
      platforms: "linux/amd64,linux/arm64"
      docker-daemon-config: |
        {
          "features": {
            "containerd-snapshotter": true
          }
        }
